-- ── TechniCasino Database Schema ──
-- Run with: sqlx migrate run
--
-- TABLES:
--
-- users
--   id            UUID PRIMARY KEY DEFAULT gen_random_uuid()
--   username      VARCHAR(20) UNIQUE NOT NULL
--   email         VARCHAR(255) UNIQUE NOT NULL
--   password_hash VARCHAR(255) NOT NULL
--   avatar_url    VARCHAR(500)
--   created_at    TIMESTAMPTZ DEFAULT NOW()
--   updated_at    TIMESTAMPTZ DEFAULT NOW()
--
-- wallets
--   id         UUID PRIMARY KEY DEFAULT gen_random_uuid()
--   user_id    UUID UNIQUE REFERENCES users(id) ON DELETE CASCADE
--   balance    BIGINT DEFAULT 0  (stored in CENTS! $10.50 = 1050)
--   created_at TIMESTAMPTZ DEFAULT NOW()
--
-- transactions
--   id            UUID PRIMARY KEY DEFAULT gen_random_uuid()
--   wallet_id     UUID REFERENCES wallets(id) ON DELETE CASCADE
--   amount        BIGINT NOT NULL  (positive=credit, negative=debit)
--   tx_type       VARCHAR(20) NOT NULL  (DEPOSIT, WITHDRAWAL, BET_PLACED, BET_WON, BET_REFUND)
--   description   TEXT
--   balance_after BIGINT NOT NULL
--   created_at    TIMESTAMPTZ DEFAULT NOW()
--
-- games
--   id             UUID PRIMARY KEY DEFAULT gen_random_uuid()
--   game_type      VARCHAR(20) NOT NULL
--   name           VARCHAR(50) NOT NULL
--   min_bet        BIGINT NOT NULL
--   max_bet        BIGINT NOT NULL
--   is_multiplayer BOOLEAN DEFAULT FALSE
--
-- game_sessions
--   id               UUID PRIMARY KEY DEFAULT gen_random_uuid()
--   user_id          UUID REFERENCES users(id)
--   game_type        VARCHAR(20) NOT NULL
--   bet_amount       BIGINT NOT NULL
--   multiplier       DECIMAL(10,4)
--   payout           BIGINT DEFAULT 0
--   outcome          VARCHAR(10)  (WIN, LOSE, PUSH)
--   state            JSONB  (game-specific state as JSON)
--   server_seed      VARCHAR(128)
--   server_seed_hash VARCHAR(128)
--   client_seed      VARCHAR(128)
--   nonce            INTEGER
--   created_at       TIMESTAMPTZ DEFAULT NOW()
--   completed_at     TIMESTAMPTZ
--
-- INDEXES:
-- CREATE INDEX idx_sessions_user ON game_sessions(user_id);
-- CREATE INDEX idx_transactions_wallet ON transactions(wallet_id);
-- CREATE INDEX idx_sessions_type ON game_sessions(game_type);
--
-- TRIGGER: Auto-create wallet when user is created.
-- INSERT default game rows.
